### ISSUE TITLE
pip can't install v.1.1.1 and v.1.1.2

### ISSUE THREAD

**Issue by inyutin** [bugov/aiohttp-basicauth-middleware#11]
Hi! Thank you for this useful package. However there is a problem. I can install v.1.1.0, but can't 1.1.1 or v.1.1.2 (the latest on pypi is 1.1.2). I think the best I can do is to attach the full log:

```
(env) ^^/C/h/modulbank_auth >>> pip install aiohttp-basicauth-middleware                                                                                                     (1) ^(*test+1807) 18:48:05
Collecting aiohttp-basicauth-middleware
  Using cached aiohttp-basicauth-middleware-1.1.2.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mac/Code/hice/modulbank_auth/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_26a2645a0afa4084aa70a88cc6531e30/setup.py'"'"'; __file__='"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_26a2645a0afa4084aa70a88cc6531e30/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-pip-egg-info-7ftu3r60
         cwd: /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_26a2645a0afa4084aa70a88cc6531e30/
    Complete output (46 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /Users/mac/Code/hice/modulbank_auth/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-wheel-qapuo0s4/http-basic-auth_caf2d39623db4043989414f86711d0b2/setup.py'"'"'; __file__='"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-wheel-qapuo0s4/http-basic-auth_caf2d39623db4043989414f86711d0b2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-wheel-j43qxcr4
           cwd: /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-wheel-qapuo0s4/http-basic-auth_caf2d39623db4043989414f86711d0b2/
      Complete output (7 lines):
      WARNING: The wheel package is not available.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for http-basic-auth
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/mac/Code/hice/modulbank_auth/env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/tmpthf1ka9q', '--quiet', 'http_basic_auth']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_26a2645a0afa4084aa70a88cc6531e30/setup.py", line 12, in <module>
        setup(
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/dist.py", line 686, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/mac/Code/hice/modulbank_auth/env/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/mac/Code/hice/modulbank_auth/env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/tmpthf1ka9q', '--quiet', 'http_basic_auth']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/89/b8/28c31077da33db6c077b3ab45b57c40a550748029c0a66d9dd00eb3d130d/aiohttp-basicauth-middleware-1.1.2.tar.gz#sha256=fb4ff3b5733ab4475dc21ecb30636542ed74c12e9eb711ac77b61795f25eb104 (from https://pypi.org/simple/aiohttp-basicauth-middleware/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading aiohttp-basicauth-middleware-1.1.1.tar.gz (4.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mac/Code/hice/modulbank_auth/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_3ad12c6dce444d14bb08a973b2ab5a8a/setup.py'"'"'; __file__='"'"'/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_3ad12c6dce444d14bb08a973b2ab5a8a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-pip-egg-info-rgjzi56r
         cwd: /private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_3ad12c6dce444d14bb08a973b2ab5a8a/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_3ad12c6dce444d14bb08a973b2ab5a8a/setup.py", line 4, in <module>
        from aiohttp_basicauth_middleware import __version__
      File "/private/var/folders/nf/762fth4x5pz1hvgj5hfl93hr0000gn/T/pip-install-wum7ddkm/aiohttp-basicauth-middleware_3ad12c6dce444d14bb08a973b2ab5a8a/aiohttp_basicauth_middleware/__init__.py", line 27, in <module>
        from http_basic_auth import parse_header, BasicAuthException
    ModuleNotFoundError: No module named 'http_basic_auth'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/69/82/ce1a48d8016bfe80a7b289955dbf8f4931add1995c4c6db4366d4f1242f4/aiohttp-basicauth-middleware-1.1.1.tar.gz#sha256=336370fcae8dc75fdab07a988f0afbedcace50968cd4a3eefa778883980a1e59 (from https://pypi.org/simple/aiohttp-basicauth-middleware/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading aiohttp_basicauth_middleware-1.1.0-py3-none-any.whl (4.8 kB)
Collecting http-basic-auth
  Using cached http-basic-auth-1.2.0.tar.gz (3.5 kB)
Requirement already satisfied: aiohttp in ./env/lib/python3.9/site-packages (from aiohttp-basicauth-middleware) (3.7.3)
Requirement already satisfied: attrs>=17.3.0 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (20.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (3.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (3.7.4.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./env/lib/python3.9/site-packages (from aiohttp->aiohttp-basicauth-middleware) (3.0.1)
Requirement already satisfied: idna>=2.0 in ./env/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp->aiohttp-basicauth-middleware) (2.10)
Using legacy 'setup.py install' for http-basic-auth, since package 'wheel' is not installed.
Installing collected packages: http-basic-auth, aiohttp-basicauth-middleware
    Running setup.py install for http-basic-auth ... done
Successfully installed aiohttp-basicauth-middleware-1.1.0 http-basic-auth-1.2.0
```

**Comment by bugov** [comment]
It looks like I forgot to define the "wheel" in the dependencies.  Please try the new version. Thank you for participating.

https://pypi.org/project/aiohttp-basicauth-middleware/1.1.3/

**Comment by inyutin** [comment]
Yep, it's workingю Thank you
