### ISSUE TITLE
Issue installing on arm/v7

### ISSUE THREAD

**Issue by marrold** [bugov/aiohttp-basicauth-middleware#14]
Hi, 

I'm trying to install  aiohttp-basicauth-middleware in a docker container built for an arm/v7 host, but I get the error below. I tried building from the master instead of latest tag which is quite old, but I got the same error.

Do you know what the issue is? Thanks

```
#9 151.1 Collecting aiohttp>=3.01
#9 151.2   Downloading aiohttp-3.8.1.tar.gz (7.3 MB)
#9 154.7   Installing build dependencies: started
#9 171.4   Installing build dependencies: finished with status 'done'
#9 171.4   Getting requirements to build wheel: started
#9 175.4   Getting requirements to build wheel: finished with status 'done'
#9 175.4   Installing backend dependencies: started
#9 182.5   Installing backend dependencies: finished with status 'done'
#9 182.5   Preparing metadata (pyproject.toml): started
#9 186.5   Preparing metadata (pyproject.toml): finished with status 'done'
#9 186.7 Collecting aiohttp-basicauth-middleware==1.1.2
#9 186.7   Downloading aiohttp-basicauth-middleware-1.1.2.tar.gz (3.9 kB)
#9 186.8   Preparing metadata (setup.py): started
#9 218.9   Preparing metadata (setup.py): finished with status 'error'
#9 218.9   ERROR: Command errored out with exit status 1:
#9 218.9    command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_7hppwit/aiohttp-basicauth-middleware_55a5eb8fffe04cb9996f73c4f8a3a5f4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_7hppwit/aiohttp-basicauth-middleware_55a5eb8fffe04cb9996f73c4f8a3a5f4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31f6ktut
#9 218.9        cwd: /tmp/pip-install-_7hppwit/aiohttp-basicauth-middleware_55a5eb8fffe04cb9996f73c4f8a3a5f4/
#9 218.9   Complete output (152 lines):
#9 218.9   /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
#9 218.9     warnings.warn(msg)
#9 218.9   warning: no files found matching 'aiohttp' anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.pyc' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.pyd' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.so' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.lib' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.dll' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.a' found anywhere in distribution
#9 218.9   warning: no previously-included files matching '*.obj' found anywhere in distribution
#9 218.9   warning: no previously-included files found matching 'aiohttp/*.html'
#9 218.9   no previously-included directories found matching 'docs/_build'
#9 218.9   Traceback (most recent call last):
#9 218.9     File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
#9 218.9       extra_postargs)
#9 218.9     File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
#9 218.9       spawn(cmd, dry_run=self.dry_run)
#9 218.9     File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
#9 218.9       _spawn_posix(cmd, search_path, dry_run=dry_run)
#9 218.9     File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
#9 218.9       % (cmd, exit_status))
#9 218.9   distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
#9 218.9
#9 218.9   During handling of the above exception, another exception occurred:
#9 218.9
#9 218.9   Traceback (most recent call last):
#9 218.9     File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
#9 218.9       dist.run_commands()
#9 218.9     File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
#9 218.9       self.run_command(cmd)
#9 218.9     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#9 218.9       cmd_obj.run()
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
#9 218.9       cmd = self.call_command('install_lib', warn_dir=0)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
#9 218.9       self.run_command(cmdname)
#9 218.9     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
#9 218.9       self.distribution.run_command(command)
#9 218.9     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#9 218.9       cmd_obj.run()
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
#9 218.9       self.build()
#9 218.9     File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
#9 218.9       self.run_command('build_ext')
#9 218.9     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
#9 218.9       self.distribution.run_command(command)
#9 218.9     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#9 218.9       cmd_obj.run()
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
#9 218.9       _build_ext.run(self)
#9 218.9     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
#9 218.9       self.build_extensions()
#9 218.9     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
#9 218.9       self._build_extensions_serial()
#9 218.9     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
#9 218.9       self.build_extension(ext)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
#9 218.9       _build_ext.build_extension(self, ext)
#9 218.9     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
#9 218.9       depends=ext.depends)
#9 218.9     File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
#9 218.9       self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
#9 218.9     File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
#9 218.9       raise CompileError(msg)
#9 218.9   distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
#9 218.9
#9 218.9   During handling of the above exception, another exception occurred:
#9 218.9
#9 218.9   Traceback (most recent call last):
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
#9 218.9       yield saved
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#9 218.9       yield
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
#9 218.9       _execfile(setup_script, ns)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
#9 218.9       exec(code, globals, locals)
#9 218.9     File "/tmp/easy_install-27ckh15p/aiohttp-4.0.0a1/setup.py", line 124, in <module>
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
#9 218.9       return distutils.core.setup(**attrs)
#9 218.9     File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
#9 218.9       raise SystemExit("error: " + str(msg))
#9 218.9   SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
#9 218.9
#9 218.9   During handling of the above exception, another exception occurred:
#9 218.9
#9 218.9   Traceback (most recent call last):
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
#9 218.9       run_setup(setup_script, args)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
#9 218.9       raise
#9 218.9     File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#9 218.9       self.gen.throw(type, value, traceback)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#9 218.9       yield
#9 218.9     File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#9 218.9       self.gen.throw(type, value, traceback)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
#9 218.9       saved_exc.resume()
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
#9 218.9       six.reraise(type, exc, self._tb)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
#9 218.9       raise value.with_traceback(tb)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
#9 218.9       yield saved
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#9 218.9       yield
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
#9 218.9       _execfile(setup_script, ns)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
#9 218.9       exec(code, globals, locals)
#9 218.9     File "/tmp/easy_install-27ckh15p/aiohttp-4.0.0a1/setup.py", line 124, in <module>
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
#9 218.9       return distutils.core.setup(**attrs)
#9 218.9     File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
#9 218.9       raise SystemExit("error: " + str(msg))
#9 218.9   SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
#9 218.9
#9 218.9   During handling of the above exception, another exception occurred:
#9 218.9
#9 218.9   Traceback (most recent call last):
#9 218.9     File "<string>", line 1, in <module>
#9 218.9     File "/tmp/pip-install-_7hppwit/aiohttp-basicauth-middleware_55a5eb8fffe04cb9996f73c4f8a3a5f4/setup.py", line 45, in <module>
#9 218.9       long_description=read('README.rst')
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
#9 218.9       _install_setup_requires(attrs)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
#9 218.9       dist.fetch_build_eggs(dist.setup_requires)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
#9 218.9       replace_conflicting=True,
#9 218.9     File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
#9 218.9       replace_conflicting=replace_conflicting
#9 218.9     File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
#9 218.9       return self.obtain(req, installer)
#9 218.9     File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
#9 218.9       return installer(requirement)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
#9 218.9       return cmd.easy_install(req)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
#9 218.9       return self.install_item(spec, dist.location, tmpdir, deps)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
#9 218.9       dists = self.install_eggs(spec, download, tmpdir)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
#9 218.9       return self.build_and_install(setup_script, setup_base)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
#9 218.9       self.run_setup(setup_script, setup_base, args)
#9 218.9     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1165, in run_setup
#9 218.9       raise DistutilsError("Setup script exited with %s" % (v.args[0],))
#9 218.9   distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
#9 218.9   **********************
#9 218.9   * Accellerated build *
#9 218.9   **********************
#9 218.9   ----------------------------------------
#9 218.9 WARNING: Discarding https://files.pythonhosted.org/packages/89/b8/28c31077da33db6c077b3ab45b57c40a550748029c0a66d9dd00eb3d130d/aiohttp-basicauth-middleware-1.1.2.tar.gz#sha256=fb4ff3b5733ab4475dc21ecb30636542ed74c12e9eb711ac77b61795f25eb104 (from https://pypi.org/simple/aiohttp-basicauth-middleware/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 218.9 ERROR: Could not find a version that satisfies the requirement aiohttp-basicauth-middleware==1.1.2 (from versions: 0.1.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3)
#9 218.9 ERROR: No matching distribution found for aiohttp-basicauth-middleware==1.1.2
```

**Comment by marrold** [comment]
Standby for now, upgrading setup tools might have resolved this issue

**Comment by bugov** [comment]
Hi! This package does not use any platform-specific features.
But it looks like you're trying to use modern versions of packages on python 3.6.
It's sad to say, but aiohttp (and many other packages) have already abandoned python<3.7.
But I've made some corrections to the requirements, and it works on py3.6.
Please try to use `aiohttp-basicauth-middleware==1.2.0`.
I hope this helps you.
