### ISSUE TITLE
Fails to install from PyPI

### ISSUE THREAD

**Issue by mdz** [bugov/aiohttp-basicauth-middleware#8]
Here's a Dockerfile illustrating the problem:

```
FROM ubuntu:18.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip

RUN pip3 install aiohttp-basicauth-middleware
```

Fails with:
```
Step 4/4 : RUN pip3 install aiohttp-basicauth-middleware
 ---> Running in 72e2ee0c4716
Collecting aiohttp-basicauth-middleware
  Downloading https://files.pythonhosted.org/packages/69/82/ce1a48d8016bfe80a7b289955dbf8f4931add1995c4c6db4366d4f1242f4/aiohttp-basicauth-middleware-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zzwt_tq8/aiohttp-basicauth-middleware/setup.py", line 4, in <module>
        from aiohttp_basicauth_middleware import __version__
      File "/tmp/pip-build-zzwt_tq8/aiohttp-basicauth-middleware/aiohttp_basicauth_middleware/__init__.py", line 26, in <module>
        from aiohttp import web
    ModuleNotFoundError: No module named 'aiohttp'
```

It seems like `setup.py egg_info` tries to import dependencies, but they haven't been installed yet when it's invoked by pip.

**Comment by bugov** [comment]
Thanks. I fixed it in v1.1.2 (already available).
